[project]
name = "mq"
version = "0.1.0"
description = "Python Code Quality Data Warehouse"
readme = "README.md"
requires-python = ">=3.11.9"
authors = [{name = "Peter Borocz", email = "peter.borocz+mq@gmail.com"}]
dependencies = [
    "peewee>=3.18.3",
    "platformdirs>=4.5.1",
    "pygal>=3.1.0",
    "python-fasthtml>=0.12.36",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "rich-argparse>=1.7.2",
]

[project.scripts]
mq = "mq.__main__:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

#-------------------------------------------------------------------------------
# Test support
#-------------------------------------------------------------------------------
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:pygal.graph.time",
]

#-----------------------------------------------------------------------------------------------
# POE Configuration and tasks:
#-----------------------------------------------------------------------------------------------
[tool.poe]
verbosity = -1

[tool.poe.tasks.Deploy]
help = "Deploy to github."
interpreter = "fish"
shell = """
  uvx cleanpy --all --exclude-envs --verbose .
  ruff rule   --all --output-format json > src/mq/tools/ruff/ruff_rules.json
  if not jj diff --quiet
    jj describe -m "chore: update ruff rules database [automated]"
  end
  jj bookmark set trunk --revision 'coalesce(@-, @)'
  jj git push --bookmark trunk

  uv run mq ingest --name python-code-quality --path https://github.com/PBorocz/mq.git
  uv run mq status --name python-code-quality
  """

[tool.poe.tasks.mq]
cmd = "uv run mq"
help = "Run the mq command"

[tool.poe.tasks.serve]
cmd = "uv run mq serve"
help = "Run the mq command"

[tool.poe.tasks.status]
cmd = "uv run mq status"
help = "Report current status"

#-------------------------------------------------------------------------------
# Ingest examples
# poe mq ingest --name python-code-quality --path "."                                          --log-level debug
# poe mq ingest --name python-code-quality --path https://github.com/PBorocz/mq.git            --log-level debug
# poe mq ingest --name optimus_ludos       --path https://github.com/PBorocz/optimus_ludos.git --log-level debug
#-------------------------------------------------------------------------------

[tool.poe.tasks.report]
cmd = """uv run mq report"""
help = "Display summary report across all modules."

#-------------------------------------------------------------------------------
# Radon - Run direct!
# uvx radon cc  . --json | uv run mq ingest --name python-code-quality --path "." --stdin --analysis radon:cc
# uvx radon hal . --json | uv run mq ingest --name python-code-quality --path "." --stdin --analysis radon:hal
# uvx radon mi  . --json | uv run mq ingest --name python-code-quality --path "." --stdin --analysis radon:mi
# uvx radon raw . --json | uv run mq ingest --name python-code-quality --path "." --stdin --analysis radon:raw
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Cloc - Run direct!
# cloc --include-lang=Python src/ --by-file --json | uv run mq ingest --stdin --name python-code-quality --path "." --analysis cloc
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Ruff (Check)  - Run direct!
# ruff check --output-format=json | uv run mq ingest --stdin --name python-code-quality --path "." --analysis ruff
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ADMIN Commands!
#-------------------------------------------------------------------------------
[tool.poe.tasks.clean]
cmd = "uv run mq admin clean"
help = "Clean the database (ie. do housekeeping) Low Risk."

[tool.poe.tasks.clear]
cmd = "uv run mq admin clear"
help = "Clear the database entirely(!) 🔥 HIGH RISK 🔥"

[tool.poe.tasks.sql]
cmd = "litecli \"~/Library/Application Support/mq/mq.sqlite3\""
help = "Run the litecli command against our persistent store."

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
