[project]
name = "mq"
version = "0.1.0"
description = "Python Code Quality Data Warehouse"
readme = "README.md"
requires-python = ">=3.11.9"
authors = [{name = "Your Name", email = "your.email@example.com"}]
dependencies = [
    "peewee>=3.18.3",
    "platformdirs>=4.5.1",
    "python-fasthtml>=0.12.36",
    "rich>=14.2.0",
]

[project.scripts]
mq = "mq.__main__:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poe]
verbosity = -1

[tool.poe.tasks.Deploy]
help = "Deploy to github."
interpreter = "fish"
shell = """
  uvx cleanpy --all --exclude-envs --verbose .
  jj bookmark set --revision  @- trunk
  jj git push     --revisions @-
  """

[tool.poe.tasks.mq]
cmd = "uv run mq"
help = "Run the mq command."

#-------------------------------------------------------------------------------
# all
#-------------------------------------------------------------------------------
[tool.poe.tasks.ingest]
cmd = """uv run mq ingest"""
help = "Run/ingest all modules."

[tool.poe.tasks.ingest-git-mq]
shell = """
  uv run mq admin clear -m cloc --no_confirm
  uv run mq ingest -m cloc --git     https://github.com/pborocz/mq
  uv run mq report -m cloc --project https://github.com/pborocz/mq --level h
  """
help = "Run/ingest all modules."

[tool.poe.tasks.report]
cmd = """uv run mq report"""
help = "Display summary report across all modules."

#-------------------------------------------------------------------------------
# Radon
#-------------------------------------------------------------------------------
[tool.poe.tasks.radon]
shell = """
  uvx radon cc  . --json | uv run mq ingest --stdin --module radon --submodule cc
  uvx radon hal . --json | uv run mq ingest --stdin --module radon --submodule hal
  uvx radon mi  . --json | uv run mq ingest --stdin --module radon --submodule mi
  uvx radon raw . --json | uv run mq ingest --stdin --module radon --submodule raw
  """
help = "Ingest radon checks"

#-------------------------------------------------------------------------------
# Cloc
#-------------------------------------------------------------------------------
[tool.poe.tasks.cloc]
shell = """
  cloc --include-lang=Python src/ --by-file --json | uv run mq ingest --module clocw
  """
help = "Run cloc and report on results."

#-------------------------------------------------------------------------------
# Ruff (Check)
#-------------------------------------------------------------------------------
[tool.poe.tasks.ruff]
shell = """
  ruff check --output-format=json | uv run mq ingest --module ruff
  """
help = "Run current ruff check and report on results."

[tool.poe.tasks.clear]
cmd = "uv run mq admin clear"
help = "Clear the database entirely(!)."

[tool.poe.tasks.trim]
cmd = "uv run mq admin trim"
help = "Delete -old- runs from the database, leaving the most recent."

[tool.poe.tasks.sql]
cmd = "litecli \"~/Library/Application Support/mq/mq.sqlite3\""
help = "Run the litecli command against our database"

#-------------------------------------------------------------------------------
# test
#-------------------------------------------------------------------------------
[tool.poe.tasks.test_suite_reports]
shell = """
  set -e
  uv run mq
  uv run mq status

  uv run mq report --module cloc
  uv run mq report --module cloc --level 0
  uv run mq report --module cloc --level 0 --options percentage
  uv run mq report --module cloc --level 1
  uv run mq report --module cloc --level 1 --options percentage
  uv run mq report --module cloc --level 2
  uv run mq report --module cloc --level 2 --options percentage
  uv run mq report --module cloc --level h

  uv run mq report --module ruff
  uv run mq report --module ruff --level 0
  uv run mq report --module ruff --level 1
  uv run mq report --module ruff --level 2
  uv run mq report --module ruff --level h
  uv run mq report --module ruff --level h --options last:99

  uv run mq report --module radon
  uv run mq report --module radon --level 0
  uv run mq report --module radon --level 1
  uv run mq report --module radon --level 2
  uv run mq report --module radon --level h
  uv run mq report --module radon --level h --options last:99

  uv run mq report --module radon --sub_module mi
  uv run mq report --module radon --sub_module mi --level 0
  uv run mq report --module radon --sub_module mi --level 1
  uv run mq report --module radon --sub_module mi --level 2
  uv run mq report --module radon --sub_module mi --level h
  uv run mq report --module radon --sub_module mi --level h --options last:99

  uv run mq report --module radon --sub_module raw
  uv run mq report --module radon --sub_module raw --level 0
  uv run mq report --module radon --sub_module raw --level 1
  uv run mq report --module radon --sub_module raw --level 2
  uv run mq report --module radon --sub_module raw --level h
  uv run mq report --module radon --sub_module raw --level h --options last:99

  uv run mq report --module radon --sub_module cc
  uv run mq report --module radon --sub_module cc --level 0
  uv run mq report --module radon --sub_module cc --level 1
  uv run mq report --module radon --sub_module cc --level 2
  uv run mq report --module radon --sub_module cc --level 3
  uv run mq report --module radon --sub_module cc --level h
  uv run mq report --module radon --sub_module cc --level h --options last:99

  uv run mq report --module radon --sub_module hal
  uv run mq report --module radon --sub_module hal --level 0
  uv run mq report --module radon --sub_module hal --level 1
  uv run mq report --module radon --sub_module hal --level 2
  uv run mq report --module radon --sub_module hal --level 3
  uv run mq report --module radon --sub_module hal --level h
  uv run mq report --module radon --sub_module hal --level h --options last:99
"""
help = "Run smoke test suite"
